package de.greenrobot.daoexample;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import de.greenrobot.daoexample.User;
import de.greenrobot.daoexample.Music;
import de.greenrobot.daoexample.MusicMessage;
import de.greenrobot.daoexample.SystemMessage;
import de.greenrobot.daoexample.ShareMessage;

import de.greenrobot.daoexample.UserDao;
import de.greenrobot.daoexample.MusicDao;
import de.greenrobot.daoexample.MusicMessageDao;
import de.greenrobot.daoexample.SystemMessageDao;
import de.greenrobot.daoexample.ShareMessageDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig musicDaoConfig;
    private final DaoConfig musicMessageDaoConfig;
    private final DaoConfig systemMessageDaoConfig;
    private final DaoConfig shareMessageDaoConfig;

    private final UserDao userDao;
    private final MusicDao musicDao;
    private final MusicMessageDao musicMessageDao;
    private final SystemMessageDao systemMessageDao;
    private final ShareMessageDao shareMessageDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        musicDaoConfig = daoConfigMap.get(MusicDao.class).clone();
        musicDaoConfig.initIdentityScope(type);

        musicMessageDaoConfig = daoConfigMap.get(MusicMessageDao.class).clone();
        musicMessageDaoConfig.initIdentityScope(type);

        systemMessageDaoConfig = daoConfigMap.get(SystemMessageDao.class).clone();
        systemMessageDaoConfig.initIdentityScope(type);

        shareMessageDaoConfig = daoConfigMap.get(ShareMessageDao.class).clone();
        shareMessageDaoConfig.initIdentityScope(type);

        userDao = new UserDao(userDaoConfig, this);
        musicDao = new MusicDao(musicDaoConfig, this);
        musicMessageDao = new MusicMessageDao(musicMessageDaoConfig, this);
        systemMessageDao = new SystemMessageDao(systemMessageDaoConfig, this);
        shareMessageDao = new ShareMessageDao(shareMessageDaoConfig, this);

        registerDao(User.class, userDao);
        registerDao(Music.class, musicDao);
        registerDao(MusicMessage.class, musicMessageDao);
        registerDao(SystemMessage.class, systemMessageDao);
        registerDao(ShareMessage.class, shareMessageDao);
    }
    
    public void clear() {
        userDaoConfig.getIdentityScope().clear();
        musicDaoConfig.getIdentityScope().clear();
        musicMessageDaoConfig.getIdentityScope().clear();
        systemMessageDaoConfig.getIdentityScope().clear();
        shareMessageDaoConfig.getIdentityScope().clear();
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public MusicDao getMusicDao() {
        return musicDao;
    }

    public MusicMessageDao getMusicMessageDao() {
        return musicMessageDao;
    }

    public SystemMessageDao getSystemMessageDao() {
        return systemMessageDao;
    }

    public ShareMessageDao getShareMessageDao() {
        return shareMessageDao;
    }

}
