package de.greenrobot.daoexample;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table SHARE_MESSAGE.
 */
public class ShareMessage {

    private Long id;
    private Long user_id;
    private Long sender_id;
    private String message;
    private String share_pic;

    public ShareMessage() {
    }

    public ShareMessage(Long id) {
        this.id = id;
    }

    public ShareMessage(Long id, Long user_id, Long sender_id, String message, String share_pic) {
        this.id = id;
        this.user_id = user_id;
        this.sender_id = sender_id;
        this.message = message;
        this.share_pic = share_pic;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getUser_id() {
        return user_id;
    }

    public void setUser_id(Long user_id) {
        this.user_id = user_id;
    }

    public Long getSender_id() {
        return sender_id;
    }

    public void setSender_id(Long sender_id) {
        this.sender_id = sender_id;
    }

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    public String getShare_pic() {
        return share_pic;
    }

    public void setShare_pic(String share_pic) {
        this.share_pic = share_pic;
    }

}
